default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: udemy_course_development
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["UDEMY_COURSE_DATABASE_PASSWORD"] %>
  host: localhost


test:
  <<: *default
  database: udemy_course_test
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["UDEMY_COURSE_DATABASE_PASSWORD"] %>
  host: localhost

production:
  primary: &primary_production
    <<: *default
    database: udemy_course_production
    username: <%= ENV["POSTGRES_USER"] %>
    password: <%= ENV["UDEMY_COURSE_DATABASE_PASSWORD"] %>
    host: localhost

  cache:
    <<: *primary_production
    database: udemy_course_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: udemy_course_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: udemy_course_production_cable
    migrations_paths: db/cable_migrate
